server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true
#      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: cloud-order-service
